- 텐서는 배열(array) 행렬(matrix)과 유사하다
- gpu나 하드웨어 가속에 사용된다는 것을 제외하면 ndarray와 동일하다


In [1]:
import torch
import numpy as np

In [ ]:
# directly 텐서 생성
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

In [ ]:
# numpy에서 생성
np_array = np.array(data)
print(np_array)
x_np = torch.from_numpy(np_array)
print(x_np)

In [8]:
# 무작위값 또는 상수 사용하기, 차원 정의하기
shape = (2,3,) # 텐서의 차원을 명시
rand_tensor = torch.rand(shape) 
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)  

tensor([[0.5387, 0.4604, 0.4356],
        [0.5946, 0.2097, 0.3576]])


In [11]:
# 텐서의 속성
print(rand_tensor.shape)
print(rand_tensor.dtype)
print(rand_tensor.device)

torch.Size([2, 3])
torch.float32
cpu


In [20]:
# 텐서의 연산(operation)

# 인덱싱, 슬라이싱
tensor = torch.ones(4, 4)
print(tensor)

print(tensor[:, 0]) # 첫번째 '열'만
print(tensor[:,-1])
print(tensor[...,-1])
tensor[:,1] = 0 # 1번 열만 0으로 바꾸기
tensor[...,-1] = 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 0.]])


In [26]:
# 텐서 합치기

# dim이 axis와 같다 0이면 행방향, 1이면 열방향
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
        [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
        [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
        [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.]])


In [31]:
# 산술연산
y1 = tensor @ tensor.T  # 전치행렬과 행렬곱
y2 = tensor.matmul(tensor.T) # 이렇게해도됨
print(y1)

y3 = torch.rand_like(y1)
print(y3)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
tensor([[0.4579, 0.4414, 0.6379, 0.5633],
        [0.9794, 0.5465, 0.6653, 0.9293],
        [0.2636, 0.2773, 0.5170, 0.9346],
        [0.8444, 0.8548, 0.7832, 0.2079]])


tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [39]:
# 요소별 곱하기
z1 = tensor * tensor
z2 = tensor.mul(tensor)
print(z1)

tensor.sum()  #모든 원소합 arregate
tensor.sum().item() # 단일 원소를 python숫자형으로 바꾸기
type(tensor.sum().item()) # float으로 나옴

tensor([[1., 0., 1., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 0.]])


float

In [40]:
# 바꿔치기 in-place
# 피연산자 operand, 연산자 operator
tensor.add_(5) # 모든 요소에 5더하기


tensor([[6., 5., 6., 5.],
        [6., 5., 6., 5.],
        [6., 5., 6., 5.],
        [6., 5., 6., 5.]])

In [46]:
# 텐서를 넘파이로 변환하기
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)
print(t.add_(1)) 
print(n)  # 텐서의 변경사항이 같이 변함

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [51]:
# 넘파이를 텐서로 변환하기

n = np.ones(5)
print(n)
t = torch.from_numpy(n)
print(t)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
